---
- hosts: localhost
  vars_files:
    - "vars/credentials.yml"
    - "vars/application-data.yml"
  tasks:
    - name: "DB instance"
      include_tasks: "01-db-instance.yml"

    - name: "Web instance"
      include_tasks: "02-web-instance.yml"

- name: deploy MySQL and configure databases
  hosts: dbservers
  # gather_facts: true
  roles:
    - db

- name: deploy apache and configure webserver
  hosts: webservers
  # gather_facts: true
  roles:
    - web
